"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-url@ux1-tmreup42y2jb!mq+7z^*ttrl#k4%=4(zzm23j*b!rj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [      
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'shoppy.apps.ShoppyConfig', 
]

AUTH_USER_MODEL = 'shoppy.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Minsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Куда отправлять для входа
LOGIN_URL = 'login' 
# Куда отправлять после успешного входа
LOGIN_REDIRECT_URL = 'catalog' 
# Куда отправлять после выхода
LOGOUT_REDIRECT_URL = 'catalog'
# ── DRF ────────────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# ── CUSTOM USER MODEL ──────────────────────────────────────────────────────
AUTH_USER_MODEL = 'shoppy.CustomUser'  # имя твоего приложения

# ── LOGIN/LOGOUT REDIRECT ──────────────────────────────────────────────────
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ── MEDIA FILES (для загрузки фото товаров) ───────────────────────────────
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ── EMAIL — Gmail SMTP ────────────────────────────────────────────────────
# ВНИМАНИЕ: не храни пароли в коде!
# Используй переменные окружения или python-decouple.
# Для Gmail нужен "Пароль приложения" (не обычный пароль):
# myaccount.google.com → Безопасность → Двухфакторная → Пароли приложений

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'antiononion@gmail.com'      # реальный Gmail
EMAIL_HOST_PASSWORD = 'sgbp hpzr surm niax' # пароль приложения Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ── MESSAGES FRAMEWORK (для flash-сообщений) ─────────────────────────────
from django.contrib.messages import constants as messages_const
MESSAGE_TAGS = {
    messages_const.DEBUG:   'info',
    messages_const.INFO:    'info',
    messages_const.SUCCESS: 'success',
    messages_const.WARNING: 'warning',
    messages_const.ERROR:   'error',
}

# ── INSTALLED_APPS — убедись, что есть все нужные ────────────────────────
# INSTALLED_APPS = [
#     ...
#     'shoppy',          # твоё приложение
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
# ]

# ── TEMPLATES — убедись, что DIRS включает папку templates ───────────────
# TEMPLATES = [{
#     ...
#     'DIRS': [BASE_DIR / 'templates'],
#     ...
# }]